name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Docker Layers
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: ./build_docker.sh
