name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Docker Build & Run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: ./build_docker.sh

      - name: Run Docker container for 3 minutes
        run: ./run_docker_with_requests.sh
